export default {
	extends: [
		'stylelint-config-standard',
	],
	plugins: [
		'stylelint-codeguide',
	],
	rules: {
		'at-rule-no-unknown': [true, {
			ignoreAtRules: [
				'import-normalize', // postcss-normalize
				'each', // postcss-each
				'layer', // tailwindcss
				'screen', // tailwindcss
			],
		}],
		'at-rule-no-vendor-prefix': true,
		'comment-empty-line-before': null,
		'custom-property-empty-line-before': 'never',
		'media-feature-name-no-vendor-prefix': true,
		'media-feature-name-no-unknown': [true, {
			ignoreMediaFeatureNames: [
				'prefers-reduced-motion',
			],
		}],
		'no-descending-specificity': null,
		'property-no-vendor-prefix': true,
		'selector-no-vendor-prefix': true,
		'selector-pseudo-class-no-unknown': [true, {
			ignorePseudoClasses: [
				'increment',
				'decrement',
				'vertical',
				'horizontal',
				'start',
				'end',
				'deep',
			],
		}],
		'value-no-vendor-prefix': true,

		// stylistic rules
		'codeguide/at-rule-name-case': 'lower',
		'codeguide/at-rule-name-space-after': 'always-single-line',
		'codeguide/at-rule-semicolon-newline-after': 'always',
		'codeguide/block-closing-brace-empty-line-before': 'never',
		'codeguide/block-closing-brace-newline-after': 'always',
		'codeguide/block-closing-brace-newline-before': 'always-multi-line',
		'codeguide/block-closing-brace-space-before': 'always-single-line',
		'codeguide/block-opening-brace-newline-after': 'always-multi-line',
		'codeguide/block-opening-brace-space-after': 'always-single-line',
		'codeguide/block-opening-brace-space-before': 'always',
		'codeguide/color-hex-case': 'lower',
		'codeguide/declaration-bang-space-after': 'never',
		'codeguide/declaration-bang-space-before': 'always',
		'codeguide/declaration-block-semicolon-newline-after': 'always-multi-line',
		'codeguide/declaration-block-semicolon-space-after': 'always-single-line',
		'codeguide/declaration-block-semicolon-space-before': 'never',
		'codeguide/declaration-block-trailing-semicolon': 'always',
		'codeguide/declaration-colon-newline-after': 'always-multi-line',
		'codeguide/declaration-colon-space-after': 'always-single-line',
		'codeguide/declaration-colon-space-before': 'never',
		'codeguide/function-comma-newline-after': 'always-multi-line',
		'codeguide/function-comma-space-after': 'always-single-line',
		'codeguide/function-comma-space-before': 'never',
		'codeguide/function-max-empty-lines': 0,
		'codeguide/function-parentheses-newline-inside': 'always-multi-line',
		'codeguide/function-parentheses-space-inside': 'never-single-line',
		'codeguide/function-whitespace-after': 'always',
		'codeguide/indentation': 'tab',
		'codeguide/max-empty-lines': 1,
		'codeguide/max-line-length': 120,
		'codeguide/media-feature-colon-space-after': 'always',
		'codeguide/media-feature-colon-space-before': 'never',
		'codeguide/media-feature-name-case': 'lower',
		'codeguide/media-feature-parentheses-space-inside': 'never',
		'codeguide/media-feature-range-operator-space-after': 'always',
		'codeguide/media-feature-range-operator-space-before': 'always',
		'codeguide/media-query-list-comma-newline-after': 'always-multi-line',
		'codeguide/media-query-list-comma-space-after': 'always-single-line',
		'codeguide/media-query-list-comma-space-before': 'never',
		'codeguide/no-empty-first-line': true,
		'codeguide/no-eol-whitespace': true,
		'codeguide/no-extra-semicolons': true,
		'codeguide/no-missing-end-of-source-newline': true,
		'codeguide/number-leading-zero': 'always',
		'codeguide/number-no-trailing-zeros': true,
		'codeguide/property-case': 'lower',
		'codeguide/selector-attribute-brackets-space-inside': 'never',
		'codeguide/selector-attribute-operator-space-after': 'never',
		'codeguide/selector-attribute-operator-space-before': 'never',
		'codeguide/selector-combinator-space-after': 'always',
		'codeguide/selector-combinator-space-before': 'always',
		'codeguide/selector-descendant-combinator-no-non-space': true,
		'codeguide/selector-list-comma-newline-after': 'always',
		'codeguide/selector-list-comma-space-before': 'never',
		'codeguide/selector-max-empty-lines': 0,
		'codeguide/selector-pseudo-class-case': 'lower',
		'codeguide/selector-pseudo-class-parentheses-space-inside': 'never',
		'codeguide/selector-pseudo-element-case': 'lower',
		'codeguide/string-quotes': 'double',
		'codeguide/unit-case': 'lower',
		'codeguide/value-list-comma-newline-after': 'always-multi-line',
		'codeguide/value-list-comma-space-after': 'always-single-line',
		'codeguide/value-list-comma-space-before': 'never',
		'codeguide/value-list-max-empty-lines': 0,
	},
};
